### ISSUE TITLE
Repos didn't update to v1.0.1

### ISSUE THREAD

**Issue by hanscg** [HENNGE/tfupdate-action#17]
Repos using tfupdate 1.0.0 didn't get any PR for Terraform 1.0.1. 
However, repo still using tfupdate 0.1.0 opened PR for Terraform 1.0.1 (https://github.com/HENNGE/shobosso-unreadchecker/pull/303)

Last week a PR was opened in repos using tfupdate 1.0.0 to update to Terraform 1.1.0 Alpha. (https://github.com/HENNGE/shobo-support-viewer/pull/73) 
Could this be a bug?

**Comment by sharu1204** [comment]
```
$ tfupdate release list hashicorp/terraform| grep -v ".*-rc[0-9]$"| sort -r
1.1.0-alpha20210616
1.0.1
1.0.0
0.15.5
0.15.4
0.15.3
0.15.2
0.13.7
0.12.31
0.11.15
```
Shall we ignore alpha version then?
